name: flutter_cgm
description: "Library for displaying CGM files in Flutter"
version: 0.0.5
repository: https://github.com/spegoraro/flutter_cgm
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  cgm:
    path: ../cgm/
    
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
